# Generated by Django 4.1.4 on 2023-01-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='movie',
            new_name='to_movie',
        ),
    ]
