# Generated by Django 4.1.4 on 2023-05-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0048_tvseries_country_of_origin'),
        ('mainhome', '0003_alter_carousel_to_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='to_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CarouselItemTVSeries', to='Movies.tvseries'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('M1', 'Movie1'), ('M2', 'Movie2'), ('M3', 'Movie3'), ('M4', 'Movie4'), ('M5', 'Movie5'), ('M6', 'Movie6'), ('d', 'Draft')], default='d', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='to_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CarouselItemMovies', to='Movies.movie'),
        ),
    ]
