# Generated by Django 4.1.4 on 2023-05-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0048_tvseries_country_of_origin'),
        ('mainhome', '0004_carousel_to_series_alter_carousel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='to_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CarouselItemMovies', to='Movies.movie'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='to_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CarouselItemTVSeries', to='Movies.tvseries'),
        ),
    ]
