# Generated by Django 4.1.4 on 2023-05-26 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import mainhome.models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0048_tvseries_country_of_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainhome', '0005_alter_carousel_to_movie_alter_carousel_to_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=mainhome.models.Profile.upload_file_name),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='Movies.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstripe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_stripe', to=settings.AUTH_USER_MODEL),
        ),
    ]
