# Generated by Django 4.1.4 on 2023-06-02 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0049_alter_movie_movie_imdb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainhome', '0006_remove_profile_description_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_movies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.CreateModel(
            name='UserMovieRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tv_series_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie_rate', to='Movies.movie')),
                ('tv_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tv_series_rate', to='Movies.tvseries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='Movies.tvseries')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tvseries_relation', to='mainhome.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='Movies.movie')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies_relation', to='mainhome.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_tvseries',
            field=models.ManyToManyField(blank=True, related_name='users_favorite_tvseries', through='mainhome.FavoriteTVSeries', to='Movies.tvseries'),
        ),
    ]
