# Generated by Django 4.1.4 on 2023-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0049_alter_movie_movie_imdb'),
        ('mainhome', '0007_remove_profile_favorite_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='user_favorite_movies', through='mainhome.FavoriteMovie', to='Movies.movie'),
        ),
    ]
