# Generated by Django 4.1.4 on 2023-06-05 21:24

from django.db import migrations, models
import mainhome.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhome', '0008_profile_profile_favorite_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=mainhome.models.Profile.upload_file_name, validators=[mainhome.models.validate_image_size]),
        ),
    ]
