# Generated by Django 4.1.4 on 2023-01-14 11:29

import Movies.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=140)),
                ('actor_surname', models.CharField(max_length=140)),
                ('actor_birthdate', models.DateField(max_length=140)),
                ('actor_slug', models.SlugField(max_length=200, unique=True)),
                ('actor_description', models.TextField()),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_producer', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=140)),
                ('company_slug', models.SlugField(max_length=200, unique=True)),
                ('company_description', models.TextField()),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=140)),
                ('producer_surname', models.CharField(max_length=140)),
                ('producer_birthdate', models.DateField()),
                ('producer_death_date', models.DateField()),
                ('producer_slug', models.SlugField(max_length=200, unique=True)),
                ('producer_description', models.TextField()),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('was_actor', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_slug', models.SlugField(unique=True)),
                ('movie_title', models.CharField(max_length=120)),
                ('movie_year', models.DateField()),
                ('movie_release_date', models.DateField()),
                ('movie_duration', models.CharField(max_length=50)),
                ('movie_imdb', models.IntegerField()),
                ('movie_topic', models.CharField(max_length=120)),
                ('movie_language', models.CharField(choices=[('EN', 'English'), ('TR', 'Türkçe'), ('TJ', 'Tajik'), ('RU', 'Russian')], default=':)', max_length=120)),
                ('movie_actors', multiselectfield.db.fields.MultiSelectField(max_length=140, verbose_name=Movies.models.Actor)),
                ('movie_image', models.FileField(blank=True, null=True, upload_to='templates/images/movies/')),
                ('thumb_url', models.CharField(blank=True, max_length=500, null=True)),
                ('thumb', models.FileField(blank=True, null=True, upload_to='images/products/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('movie_company', models.ForeignKey(default='UNDEFINED', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Movies.company')),
                ('movie_genre', models.ForeignKey(default='UNDEFINED', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Movies.category')),
                ('movie_producer', models.ForeignKey(default='UNDEFINED', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Movies.producer')),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'movie_slug')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movie')),
            ],
        ),
    ]
