# Generated by Django 4.1.4 on 2023-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
