# Generated by Django 4.1.4 on 2023-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_movie_is_published_movie_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_status',
            field=models.CharField(choices=[('RA', 'Recently Added'), ('MW', 'Most Watched'), ('TR', 'Top Rated')], max_length=5),
        ),
    ]
