# Generated by Django 4.1.4 on 2023-01-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_alter_movie_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_status',
        ),
    ]
