# Generated by Django 4.1.4 on 2023-01-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_remove_movie_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_published',
        ),
    ]
