# Generated by Django 4.1.4 on 2023-01-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_remove_movie_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views_count',
        ),
    ]
