# Generated by Django 4.1.4 on 2023-01-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_remove_movie_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
