# Generated by Django 4.1.4 on 2023-01-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_movie_is_active_movie_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_actors',
            field=models.CharField(max_length=120),
        ),
    ]
