# Generated by Django 4.1.4 on 2023-01-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_alter_actor_options_rename_movie_slug_movie_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.ManyToManyField(default='UNDEFINED', to='Movies.category'),
        ),
    ]
