# Generated by Django 4.1.4 on 2023-01-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_remove_movie_movie_genre_movie_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_MPAA_rating',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC17', 'No Children 17 and Under Admitted')], default='G', max_length=4),
        ),
    ]
