# Generated by Django 4.1.4 on 2023-01-22 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_movie_movie_mpaa_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_company',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.CharField(help_text='1h 20m', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_imdb',
            field=models.FloatField(default=5.0),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_producer',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.PositiveIntegerField(default=2023, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_actors',
            field=models.ManyToManyField(default='/N', to='Movies.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_company',
            field=models.ManyToManyField(default='UNDEFINED', to='Movies.company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_producer',
            field=models.ManyToManyField(default='UNDEFINED', to='Movies.producer'),
        ),
    ]
