# Generated by Django 4.1.4 on 2023-01-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0013_movie_movie_view_count_remove_movie_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images/movies/'),
        ),
    ]
