# Generated by Django 4.1.4 on 2023-02-01 20:30

import Movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0016_alter_movie_movie_image_alter_movie_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to=Movies.models.Movie.upload_file_name),
        ),
    ]
