# Generated by Django 4.1.4 on 2023-02-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0017_alter_movie_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailer_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
