# Generated by Django 4.1.4 on 2023-02-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0021_episode_episode_view_count_tvseries_poster_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvseries',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterIndexTogether(
            name='tvseries',
            index_together={('id', 'slug')},
        ),
    ]
