# Generated by Django 4.1.4 on 2023-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0022_alter_tvseries_options_alter_tvseries_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='IMDbid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
