# Generated by Django 4.1.4 on 2023-02-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0025_movie_fetch_data_tvseries_fetch_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fetch_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='fetch_data',
            field=models.BooleanField(default=False),
        ),
    ]
