# Generated by Django 4.1.4 on 2023-02-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0026_alter_movie_fetch_data_alter_tvseries_fetch_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvseries',
            old_name='IMDbid',
            new_name='imdb_id',
        ),
    ]
