# Generated by Django 4.1.4 on 2023-02-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0027_rename_imdbid_tvseries_imdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvseries',
            old_name='name',
            new_name='title',
        ),
    ]
