# Generated by Django 4.1.4 on 2023-03-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0029_tvseries_is_continuing_tvseries_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tv_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movies.tvseries'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='cast',
            field=models.ManyToManyField(related_name='casts', to='Movies.actor'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='director',
            field=models.ManyToManyField(related_name='directors', to='Movies.producer'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='episodes',
            field=models.ManyToManyField(related_name='episodes', to='Movies.episode'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='Movies.category'),
        ),
    ]
