# Generated by Django 4.1.4 on 2023-03-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0031_episode_imdb_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-created_at'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
