# Generated by Django 4.1.4 on 2023-03-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0033_alter_tvseries_episodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='episode',
            name='cast',
            field=models.ManyToManyField(blank=True, to='Movies.actor'),
        ),
        migrations.AddField(
            model_name='episode',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='director_producer', to='Movies.producer'),
        ),
        migrations.AddField(
            model_name='episode',
            name='original_air_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='producer_producer', to='Movies.producer'),
        ),
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='writer',
            field=models.ManyToManyField(blank=True, related_name='writer_producer', to='Movies.producer'),
        ),
        migrations.AddField(
            model_name='episode',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
