# Generated by Django 4.1.4 on 2023-03-24 00:50

import Movies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0034_rename_name_episode_title_episode_cast_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='episode',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=Movies.models.Episode.upload_file_name),
        ),
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=200, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='episode',
            index_together={('id', 'slug')},
        ),
        migrations.CreateModel(
            name='DailySeriesEpisodeViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.episode')),
            ],
        ),
    ]
