# Generated by Django 4.1.4 on 2023-03-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0035_alter_episode_options_episode_cover_episode_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
