# Generated by Django 4.1.4 on 2023-03-26 15:32

import Movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0036_alter_episode_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actor_description',
            new_name='actor_mini_biography',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='actor_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='actor_surname',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='company',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='producer_surname',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_died',
            field=models.DateField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_portrait',
            field=models.ImageField(blank=True, null=True, upload_to=Movies.models.Actor.upload_file_name),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_portrait_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producer',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_portrait',
            field=models.ImageField(blank=True, null=True, upload_to=Movies.models.Producer.upload_file_name),
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_portrait_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
