# Generated by Django 4.1.4 on 2023-03-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0037_rename_actor_description_actor_actor_mini_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
