# Generated by Django 4.1.4 on 2023-03-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0039_tvseries_writers_alter_tvseries_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='role',
            field=models.CharField(choices=[('NONE', 'NONE'), ('Writer', 'Writer'), ('Director', 'Director'), ('Executive producer', 'Executive producer'), ('Line producer', 'Line producer'), ('Supervising producer', 'Supervising producer'), ('Producer', 'Producer'), ('Co-producer', 'Co-producer'), ('Coordinating producer', 'Coordinating producer'), ('Production coordinator', 'Production coordinator'), ('Associate producer', 'Associate producer'), ('Segment producer', 'Segment producer'), ('Field producer', 'Field producer')], default='NONE', max_length=140),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='producer', to='Movies.producer'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='directors', to='Movies.producer'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='writers', to='Movies.producer'),
        ),
    ]
