# Generated by Django 4.1.4 on 2023-03-29 22:42

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0040_producer_role_tvseries_producer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_MPAA_rating',
            new_name='MPAA_rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_image',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_trailer_url',
            new_name='trailer_url',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fetch_data',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_producer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_topic',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumb_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(default='/N', related_name='movie_cast', to='Movies.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(default='.', related_name='movie_director', to='Movies.producer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(default='UNDEFINED', related_name='movie_producer', to='Movies.producer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='run_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(default='/N', related_name='movie_writer', to='Movies.producer'),
        ),
    ]
