# Generated by Django 4.1.4 on 2023-03-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0041_rename_movie_mpaa_rating_movie_mpaa_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
