# Generated by Django 4.1.4 on 2023-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0043_movie_votes_alter_movie_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
