# Generated by Django 4.1.4 on 2023-05-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0045_watchmovieurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorRoleByMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_act', to='Movies.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_role_on_ep', to='Movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ActorRoleByEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_act', to='Movies.actor')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_role', to='Movies.episode')),
            ],
        ),
    ]
