# Generated by Django 4.1.4 on 2023-05-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0046_actorrolebymovie_actorrolebyepisode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MPAA_rating',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'No Children 17 and Under Admitted')], default='G', max_length=6),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='MPAA_rating',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'No Children 17 and Under Admitted')], default='G', max_length=6),
        ),
    ]
