# Generated by Django 4.1.4 on 2023-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0048_tvseries_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_imdb',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
    ]
